apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: post-api
spec:
  interval: 5m
  chart:
    spec:
      chart: app
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: homelab
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    nodeSelector:
      kubernetes.io/arch: amd64
      kubernetes.io/os: linux

    image:
      repository: "ghcr.io/toledompm/post-api"
      pullPolicy: IfNotPresent
      tag: "0.3.0"

    secretEnv: post-api-env
    secretFiles:
      - name: post-api-oci
        mountPath: /root/.oci/

    service:
      type: ClusterIP
      port: 3030

    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: blog-api.toledompm.xyz
        external-dns.alpha.kubernetes.io/target: cluster.toledompm.xyz
      hosts:
        - host: blog-api.toledompm.xyz
          paths:
            - path: /api
              pathType: Prefix

    resources:
      limits:
        cpu: 100m
        memory: 256Mi

    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
